version: '2'
services:

  app-service:
    restart: always
    image: docker.juandiii.com/app
    ports:
      - "8080"

  app2-service:
    restart: always
    image: docker.juandiii.com/app
    ports:
      - "8081"

  app3-service:
    restart: always
    image: docker.juandiii.com/app
    ports:
      - "8082"

  ha-proxy:
    restart: always
    image: haproxy:2.0.2
    volumes:
    - ./etc:/usr/local/etc/haproxy
    ports:
      - "80:80"
