version: '2'
services:

  app-service:
    restart: always
    image: docker.juandiii.com/app
    environment:
      - SERVER_PORT=8080
    depends_on:
      - mariadb
    ports:
      - "8080"

  app2-service:
    restart: always
    image: docker.juandiii.com/app
    environment:
      - SERVER_PORT=8081
    depends_on:
      - mariadb
    ports:
      - "8081"

  app3-service:
    restart: always
    image: docker.juandiii.com/app
    environment:
      - SERVER_PORT=8082
    depends_on:
      - mariadb
    ports:
      - "8082"

  ha-proxy:
    restart: always
    depends_on:
      - app-service
      - app2-service
      - app3-service
    image: haproxy:2.0.2
    volumes:
      - ./etc:/usr/local/etc/haproxy
    ports:
      - "80:80"

  mariadb:
    container_name: mariadb
    restart: always
    image: mariadb:10.2
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: p@ssw0rd
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: login
    volumes:
      - mysql_db:/var/lib/mysql
volumes:
  mysql_db:

networks:
  default:
    external:
      name: docker_default
